package com.ray.demo.admin.model.master;

import java.io.Serializable;
import java.util.Date;

public class BankAccount implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_account.id
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_account.bank_id
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    private Long bankId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_account.account_name
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    private String accountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_account.phone
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_account.account_type
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    private String accountType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_account.account
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_account.account_alias
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    private String accountAlias;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_account.notes
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    private String notes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_account.delete_flag
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    private Integer deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_account.status
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_account.creator
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    private Long creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_account.create_time
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_account.modifier
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    private Long modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_account.modify_time
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_account.company_id
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    private Long companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bank_account
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.id
     *
     * @return the value of bank_account.id
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.id
     *
     * @param id the value for bank_account.id
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.bank_id
     *
     * @return the value of bank_account.bank_id
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public Long getBankId() {
        return bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.bank_id
     *
     * @param bankId the value for bank_account.bank_id
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public void setBankId(Long bankId) {
        this.bankId = bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.account_name
     *
     * @return the value of bank_account.account_name
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.account_name
     *
     * @param accountName the value for bank_account.account_name
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.phone
     *
     * @return the value of bank_account.phone
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.phone
     *
     * @param phone the value for bank_account.phone
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.account_type
     *
     * @return the value of bank_account.account_type
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.account_type
     *
     * @param accountType the value for bank_account.account_type
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public void setAccountType(String accountType) {
        this.accountType = accountType == null ? null : accountType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.account
     *
     * @return the value of bank_account.account
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.account
     *
     * @param account the value for bank_account.account
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.account_alias
     *
     * @return the value of bank_account.account_alias
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public String getAccountAlias() {
        return accountAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.account_alias
     *
     * @param accountAlias the value for bank_account.account_alias
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public void setAccountAlias(String accountAlias) {
        this.accountAlias = accountAlias == null ? null : accountAlias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.notes
     *
     * @return the value of bank_account.notes
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.notes
     *
     * @param notes the value for bank_account.notes
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public void setNotes(String notes) {
        this.notes = notes == null ? null : notes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.delete_flag
     *
     * @return the value of bank_account.delete_flag
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.delete_flag
     *
     * @param deleteFlag the value for bank_account.delete_flag
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.status
     *
     * @return the value of bank_account.status
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.status
     *
     * @param status the value for bank_account.status
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.creator
     *
     * @return the value of bank_account.creator
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.creator
     *
     * @param creator the value for bank_account.creator
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.create_time
     *
     * @return the value of bank_account.create_time
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.create_time
     *
     * @param createTime the value for bank_account.create_time
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.modifier
     *
     * @return the value of bank_account.modifier
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public Long getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.modifier
     *
     * @param modifier the value for bank_account.modifier
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public void setModifier(Long modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.modify_time
     *
     * @return the value of bank_account.modify_time
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.modify_time
     *
     * @param modifyTime the value for bank_account.modify_time
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.company_id
     *
     * @return the value of bank_account.company_id
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.company_id
     *
     * @param companyId the value for bank_account.company_id
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }
}