package com.ray.demo.admin.model.master;

import java.io.Serializable;
import java.util.Date;

public class Bank implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank.id
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank.bank_name
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    private String bankName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank.bank_code
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    private String bankCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank.bank_type
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    private Integer bankType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank.bank_address
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    private String bankAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank.contact_name
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    private String contactName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank.contact_phone
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    private String contactPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank.status
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank.delete_flag
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    private Integer deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank.notes
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    private String notes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank.creator
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    private Long creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank.create_time
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank.modifier
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    private Long modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank.modify_time
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bank
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank.id
     *
     * @return the value of bank.id
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank.id
     *
     * @param id the value for bank.id
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank.bank_name
     *
     * @return the value of bank.bank_name
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank.bank_name
     *
     * @param bankName the value for bank.bank_name
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank.bank_code
     *
     * @return the value of bank.bank_code
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    public String getBankCode() {
        return bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank.bank_code
     *
     * @param bankCode the value for bank.bank_code
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode == null ? null : bankCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank.bank_type
     *
     * @return the value of bank.bank_type
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    public Integer getBankType() {
        return bankType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank.bank_type
     *
     * @param bankType the value for bank.bank_type
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    public void setBankType(Integer bankType) {
        this.bankType = bankType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank.bank_address
     *
     * @return the value of bank.bank_address
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    public String getBankAddress() {
        return bankAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank.bank_address
     *
     * @param bankAddress the value for bank.bank_address
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    public void setBankAddress(String bankAddress) {
        this.bankAddress = bankAddress == null ? null : bankAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank.contact_name
     *
     * @return the value of bank.contact_name
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank.contact_name
     *
     * @param contactName the value for bank.contact_name
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    public void setContactName(String contactName) {
        this.contactName = contactName == null ? null : contactName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank.contact_phone
     *
     * @return the value of bank.contact_phone
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank.contact_phone
     *
     * @param contactPhone the value for bank.contact_phone
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone == null ? null : contactPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank.status
     *
     * @return the value of bank.status
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank.status
     *
     * @param status the value for bank.status
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank.delete_flag
     *
     * @return the value of bank.delete_flag
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank.delete_flag
     *
     * @param deleteFlag the value for bank.delete_flag
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank.notes
     *
     * @return the value of bank.notes
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank.notes
     *
     * @param notes the value for bank.notes
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    public void setNotes(String notes) {
        this.notes = notes == null ? null : notes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank.creator
     *
     * @return the value of bank.creator
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank.creator
     *
     * @param creator the value for bank.creator
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank.create_time
     *
     * @return the value of bank.create_time
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank.create_time
     *
     * @param createTime the value for bank.create_time
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank.modifier
     *
     * @return the value of bank.modifier
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    public Long getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank.modifier
     *
     * @param modifier the value for bank.modifier
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    public void setModifier(Long modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank.modify_time
     *
     * @return the value of bank.modify_time
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank.modify_time
     *
     * @param modifyTime the value for bank.modify_time
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}