package com.ray.demo.admin.model.master;

import java.io.Serializable;
import java.util.Date;

public class CodeRuleVo implements Serializable {
//	private String lesscode;
	
	private Long id;
	private String sellerAddress;
	
	private String   contractCode;
	private Long leasingRequestId;//融资租赁申请号
	private String type1;//客户类型
	private String businessType;//业务类型
	private Long lessingRequestId;//   通过lessing_equest id   来获得客户类型和业务类型
	
	public Long getLeasingRequestId() {
		return leasingRequestId;
	}

	public void setLeasingRequestId(Long leasingRequestId) {
		this.leasingRequestId = leasingRequestId;
	}

	private String code;//
		public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

		public Long getLessingRequestId() {
		return lessingRequestId;
	}

	public void setLessingRequestId(Long lessingRequestId) {
		this.lessingRequestId = lessingRequestId;
	}

		public String getType1() {
		return type1;
	}

	public void setType1(String type1) {
		this.type1 = type1;
	}

	public String getBusinessType() {
		return businessType;
	}

	public void setBusinessType(String businessType) {
		this.businessType = businessType;
	}

		public String getContractCode() {
		return contractCode;
	}

	public void setContractCode(String contractCode) {
		this.contractCode = contractCode;
	}

		public String getSellerAddress() {
		return sellerAddress;
	}

	public void setSellerAddress(String sellerAddress) {
		this.sellerAddress = sellerAddress;
	}

		/**
	     *
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column code_rule.type
	     *
	     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
	     */
	    private String type;

	    /**
	     *
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column code_rule.expression
	     *
	     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
	     */
	    private String expression;

	    /**
	     *
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column code_rule.serial
	     *
	     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
	     */
	    private Long serial;

	    /**
	     *
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column code_rule.serial_length
	     *
	     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
	     */
	    private Integer serialLength;

	    /**
	     *
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column code_rule.reset_type
	     *
	     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
	     */
	    private Integer resetType;

	    /**
	     *
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column code_rule.delete_flag
	     *
	     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
	     */
	    private Integer deleteFlag;

	    /**
	     *
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column code_rule.creator
	     *
	     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
	     */
	    private Long creator;

	    /**
	     *
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column code_rule.create_time
	     *
	     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
	     */
	    private Date createTime;

	    /**
	     *
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column code_rule.modifier
	     *
	     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
	     */
	    private Long modifier;

	    /**
	     *
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column code_rule.modify_time
	     *
	     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
	     */
	    private Date modifyTime;

	    /**
	     *
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column code_rule.status
	     *
	     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
	     */
	    private Integer status;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database table code_rule
	     *
	     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
	     */
	    private static final long serialVersionUID = 1L;

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column code_rule.id
	     *
	     * @return the value of code_rule.id
	     *
	     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
	     */
	    public Long getId() {
	        return id;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column code_rule.id
	     *
	     * @param id the value for code_rule.id
	     *
	     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
	     */
	    public void setId(Long id) {
	        this.id = id;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column code_rule.type
	     *
	     * @return the value of code_rule.type
	     *
	     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
	     */
	    public String getType() {
	        return type;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column code_rule.type
	     *
	     * @param type the value for code_rule.type
	     *
	     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
	     */
	    public void setType(String type) {
	        this.type = type == null ? null : type.trim();
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column code_rule.expression
	     *
	     * @return the value of code_rule.expression
	     *
	     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
	     */
	    public String getExpression() {
	        return expression;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column code_rule.expression
	     *
	     * @param expression the value for code_rule.expression
	     *
	     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
	     */
	    public void setExpression(String expression) {
	        this.expression = expression == null ? null : expression.trim();
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column code_rule.serial
	     *
	     * @return the value of code_rule.serial
	     *
	     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
	     */
	    public Long getSerial() {
	        return serial;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column code_rule.serial
	     *
	     * @param serial the value for code_rule.serial
	     *
	     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
	     */
	    public void setSerial(Long serial) {
	        this.serial = serial;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column code_rule.serial_length
	     *
	     * @return the value of code_rule.serial_length
	     *
	     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
	     */
	    public Integer getSerialLength() {
	        return serialLength;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column code_rule.serial_length
	     *
	     * @param serialLength the value for code_rule.serial_length
	     *
	     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
	     */
	    public void setSerialLength(Integer serialLength) {
	        this.serialLength = serialLength;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column code_rule.reset_type
	     *
	     * @return the value of code_rule.reset_type
	     *
	     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
	     */
	    public Integer getResetType() {
	        return resetType;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column code_rule.reset_type
	     *
	     * @param resetType the value for code_rule.reset_type
	     *
	     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
	     */
	    public void setResetType(Integer resetType) {
	        this.resetType = resetType;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column code_rule.delete_flag
	     *
	     * @return the value of code_rule.delete_flag
	     *
	     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
	     */
	    public Integer getDeleteFlag() {
	        return deleteFlag;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column code_rule.delete_flag
	     *
	     * @param deleteFlag the value for code_rule.delete_flag
	     *
	     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
	     */
	    public void setDeleteFlag(Integer deleteFlag) {
	        this.deleteFlag = deleteFlag;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column code_rule.creator
	     *
	     * @return the value of code_rule.creator
	     *
	     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
	     */
	    public Long getCreator() {
	        return creator;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column code_rule.creator
	     *
	     * @param creator the value for code_rule.creator
	     *
	     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
	     */
	    public void setCreator(Long creator) {
	        this.creator = creator;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column code_rule.create_time
	     *
	     * @return the value of code_rule.create_time
	     *
	     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
	     */
	    public Date getCreateTime() {
	        return createTime;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column code_rule.create_time
	     *
	     * @param createTime the value for code_rule.create_time
	     *
	     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
	     */
	    public void setCreateTime(Date createTime) {
	        this.createTime = createTime;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column code_rule.modifier
	     *
	     * @return the value of code_rule.modifier
	     *
	     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
	     */
	    public Long getModifier() {
	        return modifier;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column code_rule.modifier
	     *
	     * @param modifier the value for code_rule.modifier
	     *
	     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
	     */
	    public void setModifier(Long modifier) {
	        this.modifier = modifier;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column code_rule.modify_time
	     *
	     * @return the value of code_rule.modify_time
	     *
	     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
	     */
	    public Date getModifyTime() {
	        return modifyTime;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column code_rule.modify_time
	     *
	     * @param modifyTime the value for code_rule.modify_time
	     *
	     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
	     */
	    public void setModifyTime(Date modifyTime) {
	        this.modifyTime = modifyTime;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column code_rule.status
	     *
	     * @return the value of code_rule.status
	     *
	     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
	     */
	    public Integer getStatus() {
	        return status;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column code_rule.status
	     *
	     * @param status the value for code_rule.status
	     *
	     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
	     */
	    public void setStatus(Integer status) {
	        this.status = status;
	    }

}