package com.ray.demo.admin.model.master;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class InterestExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table interest
	 * @mbggenerated  Mon Aug 29 09:30:58 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table interest
	 * @mbggenerated  Mon Aug 29 09:30:58 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table interest
	 * @mbggenerated  Mon Aug 29 09:30:58 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interest
	 * @mbggenerated  Mon Aug 29 09:30:58 CST 2016
	 */
	public InterestExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interest
	 * @mbggenerated  Mon Aug 29 09:30:58 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interest
	 * @mbggenerated  Mon Aug 29 09:30:58 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interest
	 * @mbggenerated  Mon Aug 29 09:30:58 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interest
	 * @mbggenerated  Mon Aug 29 09:30:58 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interest
	 * @mbggenerated  Mon Aug 29 09:30:58 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interest
	 * @mbggenerated  Mon Aug 29 09:30:58 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interest
	 * @mbggenerated  Mon Aug 29 09:30:58 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interest
	 * @mbggenerated  Mon Aug 29 09:30:58 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interest
	 * @mbggenerated  Mon Aug 29 09:30:58 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interest
	 * @mbggenerated  Mon Aug 29 09:30:58 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table interest
	 * @mbggenerated  Mon Aug 29 09:30:58 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andInterestDateIsNull() {
			addCriterion("interest_date is null");
			return (Criteria) this;
		}

		public Criteria andInterestDateIsNotNull() {
			addCriterion("interest_date is not null");
			return (Criteria) this;
		}

		public Criteria andInterestDateEqualTo(Date value) {
			addCriterion("interest_date =", value, "interestDate");
			return (Criteria) this;
		}

		public Criteria andInterestDateNotEqualTo(Date value) {
			addCriterion("interest_date <>", value, "interestDate");
			return (Criteria) this;
		}

		public Criteria andInterestDateGreaterThan(Date value) {
			addCriterion("interest_date >", value, "interestDate");
			return (Criteria) this;
		}

		public Criteria andInterestDateGreaterThanOrEqualTo(Date value) {
			addCriterion("interest_date >=", value, "interestDate");
			return (Criteria) this;
		}

		public Criteria andInterestDateLessThan(Date value) {
			addCriterion("interest_date <", value, "interestDate");
			return (Criteria) this;
		}

		public Criteria andInterestDateLessThanOrEqualTo(Date value) {
			addCriterion("interest_date <=", value, "interestDate");
			return (Criteria) this;
		}

		public Criteria andInterestDateIn(List<Date> values) {
			addCriterion("interest_date in", values, "interestDate");
			return (Criteria) this;
		}

		public Criteria andInterestDateNotIn(List<Date> values) {
			addCriterion("interest_date not in", values, "interestDate");
			return (Criteria) this;
		}

		public Criteria andInterestDateBetween(Date value1, Date value2) {
			addCriterion("interest_date between", value1, value2, "interestDate");
			return (Criteria) this;
		}

		public Criteria andInterestDateNotBetween(Date value1, Date value2) {
			addCriterion("interest_date not between", value1, value2, "interestDate");
			return (Criteria) this;
		}

		public Criteria andHalfYearIsNull() {
			addCriterion("half_year is null");
			return (Criteria) this;
		}

		public Criteria andHalfYearIsNotNull() {
			addCriterion("half_year is not null");
			return (Criteria) this;
		}

		public Criteria andHalfYearEqualTo(Double value) {
			addCriterion("half_year =", value, "halfYear");
			return (Criteria) this;
		}

		public Criteria andHalfYearNotEqualTo(Double value) {
			addCriterion("half_year <>", value, "halfYear");
			return (Criteria) this;
		}

		public Criteria andHalfYearGreaterThan(Double value) {
			addCriterion("half_year >", value, "halfYear");
			return (Criteria) this;
		}

		public Criteria andHalfYearGreaterThanOrEqualTo(Double value) {
			addCriterion("half_year >=", value, "halfYear");
			return (Criteria) this;
		}

		public Criteria andHalfYearLessThan(Double value) {
			addCriterion("half_year <", value, "halfYear");
			return (Criteria) this;
		}

		public Criteria andHalfYearLessThanOrEqualTo(Double value) {
			addCriterion("half_year <=", value, "halfYear");
			return (Criteria) this;
		}

		public Criteria andHalfYearIn(List<Double> values) {
			addCriterion("half_year in", values, "halfYear");
			return (Criteria) this;
		}

		public Criteria andHalfYearNotIn(List<Double> values) {
			addCriterion("half_year not in", values, "halfYear");
			return (Criteria) this;
		}

		public Criteria andHalfYearBetween(Double value1, Double value2) {
			addCriterion("half_year between", value1, value2, "halfYear");
			return (Criteria) this;
		}

		public Criteria andHalfYearNotBetween(Double value1, Double value2) {
			addCriterion("half_year not between", value1, value2, "halfYear");
			return (Criteria) this;
		}

		public Criteria andOneYearIsNull() {
			addCriterion("one_year is null");
			return (Criteria) this;
		}

		public Criteria andOneYearIsNotNull() {
			addCriterion("one_year is not null");
			return (Criteria) this;
		}

		public Criteria andOneYearEqualTo(Double value) {
			addCriterion("one_year =", value, "oneYear");
			return (Criteria) this;
		}

		public Criteria andOneYearNotEqualTo(Double value) {
			addCriterion("one_year <>", value, "oneYear");
			return (Criteria) this;
		}

		public Criteria andOneYearGreaterThan(Double value) {
			addCriterion("one_year >", value, "oneYear");
			return (Criteria) this;
		}

		public Criteria andOneYearGreaterThanOrEqualTo(Double value) {
			addCriterion("one_year >=", value, "oneYear");
			return (Criteria) this;
		}

		public Criteria andOneYearLessThan(Double value) {
			addCriterion("one_year <", value, "oneYear");
			return (Criteria) this;
		}

		public Criteria andOneYearLessThanOrEqualTo(Double value) {
			addCriterion("one_year <=", value, "oneYear");
			return (Criteria) this;
		}

		public Criteria andOneYearIn(List<Double> values) {
			addCriterion("one_year in", values, "oneYear");
			return (Criteria) this;
		}

		public Criteria andOneYearNotIn(List<Double> values) {
			addCriterion("one_year not in", values, "oneYear");
			return (Criteria) this;
		}

		public Criteria andOneYearBetween(Double value1, Double value2) {
			addCriterion("one_year between", value1, value2, "oneYear");
			return (Criteria) this;
		}

		public Criteria andOneYearNotBetween(Double value1, Double value2) {
			addCriterion("one_year not between", value1, value2, "oneYear");
			return (Criteria) this;
		}

		public Criteria andThreeYearIsNull() {
			addCriterion("three_year is null");
			return (Criteria) this;
		}

		public Criteria andThreeYearIsNotNull() {
			addCriterion("three_year is not null");
			return (Criteria) this;
		}

		public Criteria andThreeYearEqualTo(Double value) {
			addCriterion("three_year =", value, "threeYear");
			return (Criteria) this;
		}

		public Criteria andThreeYearNotEqualTo(Double value) {
			addCriterion("three_year <>", value, "threeYear");
			return (Criteria) this;
		}

		public Criteria andThreeYearGreaterThan(Double value) {
			addCriterion("three_year >", value, "threeYear");
			return (Criteria) this;
		}

		public Criteria andThreeYearGreaterThanOrEqualTo(Double value) {
			addCriterion("three_year >=", value, "threeYear");
			return (Criteria) this;
		}

		public Criteria andThreeYearLessThan(Double value) {
			addCriterion("three_year <", value, "threeYear");
			return (Criteria) this;
		}

		public Criteria andThreeYearLessThanOrEqualTo(Double value) {
			addCriterion("three_year <=", value, "threeYear");
			return (Criteria) this;
		}

		public Criteria andThreeYearIn(List<Double> values) {
			addCriterion("three_year in", values, "threeYear");
			return (Criteria) this;
		}

		public Criteria andThreeYearNotIn(List<Double> values) {
			addCriterion("three_year not in", values, "threeYear");
			return (Criteria) this;
		}

		public Criteria andThreeYearBetween(Double value1, Double value2) {
			addCriterion("three_year between", value1, value2, "threeYear");
			return (Criteria) this;
		}

		public Criteria andThreeYearNotBetween(Double value1, Double value2) {
			addCriterion("three_year not between", value1, value2, "threeYear");
			return (Criteria) this;
		}

		public Criteria andFiveYearIsNull() {
			addCriterion("five_year is null");
			return (Criteria) this;
		}

		public Criteria andFiveYearIsNotNull() {
			addCriterion("five_year is not null");
			return (Criteria) this;
		}

		public Criteria andFiveYearEqualTo(Double value) {
			addCriterion("five_year =", value, "fiveYear");
			return (Criteria) this;
		}

		public Criteria andFiveYearNotEqualTo(Double value) {
			addCriterion("five_year <>", value, "fiveYear");
			return (Criteria) this;
		}

		public Criteria andFiveYearGreaterThan(Double value) {
			addCriterion("five_year >", value, "fiveYear");
			return (Criteria) this;
		}

		public Criteria andFiveYearGreaterThanOrEqualTo(Double value) {
			addCriterion("five_year >=", value, "fiveYear");
			return (Criteria) this;
		}

		public Criteria andFiveYearLessThan(Double value) {
			addCriterion("five_year <", value, "fiveYear");
			return (Criteria) this;
		}

		public Criteria andFiveYearLessThanOrEqualTo(Double value) {
			addCriterion("five_year <=", value, "fiveYear");
			return (Criteria) this;
		}

		public Criteria andFiveYearIn(List<Double> values) {
			addCriterion("five_year in", values, "fiveYear");
			return (Criteria) this;
		}

		public Criteria andFiveYearNotIn(List<Double> values) {
			addCriterion("five_year not in", values, "fiveYear");
			return (Criteria) this;
		}

		public Criteria andFiveYearBetween(Double value1, Double value2) {
			addCriterion("five_year between", value1, value2, "fiveYear");
			return (Criteria) this;
		}

		public Criteria andFiveYearNotBetween(Double value1, Double value2) {
			addCriterion("five_year not between", value1, value2, "fiveYear");
			return (Criteria) this;
		}

		public Criteria andFiveYearAboveIsNull() {
			addCriterion("five_year_above is null");
			return (Criteria) this;
		}

		public Criteria andFiveYearAboveIsNotNull() {
			addCriterion("five_year_above is not null");
			return (Criteria) this;
		}

		public Criteria andFiveYearAboveEqualTo(Double value) {
			addCriterion("five_year_above =", value, "fiveYearAbove");
			return (Criteria) this;
		}

		public Criteria andFiveYearAboveNotEqualTo(Double value) {
			addCriterion("five_year_above <>", value, "fiveYearAbove");
			return (Criteria) this;
		}

		public Criteria andFiveYearAboveGreaterThan(Double value) {
			addCriterion("five_year_above >", value, "fiveYearAbove");
			return (Criteria) this;
		}

		public Criteria andFiveYearAboveGreaterThanOrEqualTo(Double value) {
			addCriterion("five_year_above >=", value, "fiveYearAbove");
			return (Criteria) this;
		}

		public Criteria andFiveYearAboveLessThan(Double value) {
			addCriterion("five_year_above <", value, "fiveYearAbove");
			return (Criteria) this;
		}

		public Criteria andFiveYearAboveLessThanOrEqualTo(Double value) {
			addCriterion("five_year_above <=", value, "fiveYearAbove");
			return (Criteria) this;
		}

		public Criteria andFiveYearAboveIn(List<Double> values) {
			addCriterion("five_year_above in", values, "fiveYearAbove");
			return (Criteria) this;
		}

		public Criteria andFiveYearAboveNotIn(List<Double> values) {
			addCriterion("five_year_above not in", values, "fiveYearAbove");
			return (Criteria) this;
		}

		public Criteria andFiveYearAboveBetween(Double value1, Double value2) {
			addCriterion("five_year_above between", value1, value2, "fiveYearAbove");
			return (Criteria) this;
		}

		public Criteria andFiveYearAboveNotBetween(Double value1, Double value2) {
			addCriterion("five_year_above not between", value1, value2, "fiveYearAbove");
			return (Criteria) this;
		}

		public Criteria andDeleteFlagIsNull() {
			addCriterion("delete_flag is null");
			return (Criteria) this;
		}

		public Criteria andDeleteFlagIsNotNull() {
			addCriterion("delete_flag is not null");
			return (Criteria) this;
		}

		public Criteria andDeleteFlagEqualTo(Integer value) {
			addCriterion("delete_flag =", value, "deleteFlag");
			return (Criteria) this;
		}

		public Criteria andDeleteFlagNotEqualTo(Integer value) {
			addCriterion("delete_flag <>", value, "deleteFlag");
			return (Criteria) this;
		}

		public Criteria andDeleteFlagGreaterThan(Integer value) {
			addCriterion("delete_flag >", value, "deleteFlag");
			return (Criteria) this;
		}

		public Criteria andDeleteFlagGreaterThanOrEqualTo(Integer value) {
			addCriterion("delete_flag >=", value, "deleteFlag");
			return (Criteria) this;
		}

		public Criteria andDeleteFlagLessThan(Integer value) {
			addCriterion("delete_flag <", value, "deleteFlag");
			return (Criteria) this;
		}

		public Criteria andDeleteFlagLessThanOrEqualTo(Integer value) {
			addCriterion("delete_flag <=", value, "deleteFlag");
			return (Criteria) this;
		}

		public Criteria andDeleteFlagIn(List<Integer> values) {
			addCriterion("delete_flag in", values, "deleteFlag");
			return (Criteria) this;
		}

		public Criteria andDeleteFlagNotIn(List<Integer> values) {
			addCriterion("delete_flag not in", values, "deleteFlag");
			return (Criteria) this;
		}

		public Criteria andDeleteFlagBetween(Integer value1, Integer value2) {
			addCriterion("delete_flag between", value1, value2, "deleteFlag");
			return (Criteria) this;
		}

		public Criteria andDeleteFlagNotBetween(Integer value1, Integer value2) {
			addCriterion("delete_flag not between", value1, value2, "deleteFlag");
			return (Criteria) this;
		}

		public Criteria andNotesIsNull() {
			addCriterion("notes is null");
			return (Criteria) this;
		}

		public Criteria andNotesIsNotNull() {
			addCriterion("notes is not null");
			return (Criteria) this;
		}

		public Criteria andNotesEqualTo(String value) {
			addCriterion("notes =", value, "notes");
			return (Criteria) this;
		}

		public Criteria andNotesNotEqualTo(String value) {
			addCriterion("notes <>", value, "notes");
			return (Criteria) this;
		}

		public Criteria andNotesGreaterThan(String value) {
			addCriterion("notes >", value, "notes");
			return (Criteria) this;
		}

		public Criteria andNotesGreaterThanOrEqualTo(String value) {
			addCriterion("notes >=", value, "notes");
			return (Criteria) this;
		}

		public Criteria andNotesLessThan(String value) {
			addCriterion("notes <", value, "notes");
			return (Criteria) this;
		}

		public Criteria andNotesLessThanOrEqualTo(String value) {
			addCriterion("notes <=", value, "notes");
			return (Criteria) this;
		}

		public Criteria andNotesLike(String value) {
			addCriterion("notes like", value, "notes");
			return (Criteria) this;
		}

		public Criteria andNotesNotLike(String value) {
			addCriterion("notes not like", value, "notes");
			return (Criteria) this;
		}

		public Criteria andNotesIn(List<String> values) {
			addCriterion("notes in", values, "notes");
			return (Criteria) this;
		}

		public Criteria andNotesNotIn(List<String> values) {
			addCriterion("notes not in", values, "notes");
			return (Criteria) this;
		}

		public Criteria andNotesBetween(String value1, String value2) {
			addCriterion("notes between", value1, value2, "notes");
			return (Criteria) this;
		}

		public Criteria andNotesNotBetween(String value1, String value2) {
			addCriterion("notes not between", value1, value2, "notes");
			return (Criteria) this;
		}

		public Criteria andCreatorIsNull() {
			addCriterion("creator is null");
			return (Criteria) this;
		}

		public Criteria andCreatorIsNotNull() {
			addCriterion("creator is not null");
			return (Criteria) this;
		}

		public Criteria andCreatorEqualTo(Long value) {
			addCriterion("creator =", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorNotEqualTo(Long value) {
			addCriterion("creator <>", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorGreaterThan(Long value) {
			addCriterion("creator >", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorGreaterThanOrEqualTo(Long value) {
			addCriterion("creator >=", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorLessThan(Long value) {
			addCriterion("creator <", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorLessThanOrEqualTo(Long value) {
			addCriterion("creator <=", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorIn(List<Long> values) {
			addCriterion("creator in", values, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorNotIn(List<Long> values) {
			addCriterion("creator not in", values, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorBetween(Long value1, Long value2) {
			addCriterion("creator between", value1, value2, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorNotBetween(Long value1, Long value2) {
			addCriterion("creator not between", value1, value2, "creator");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andModifierIsNull() {
			addCriterion("modifier is null");
			return (Criteria) this;
		}

		public Criteria andModifierIsNotNull() {
			addCriterion("modifier is not null");
			return (Criteria) this;
		}

		public Criteria andModifierEqualTo(Long value) {
			addCriterion("modifier =", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierNotEqualTo(Long value) {
			addCriterion("modifier <>", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierGreaterThan(Long value) {
			addCriterion("modifier >", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierGreaterThanOrEqualTo(Long value) {
			addCriterion("modifier >=", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierLessThan(Long value) {
			addCriterion("modifier <", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierLessThanOrEqualTo(Long value) {
			addCriterion("modifier <=", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierIn(List<Long> values) {
			addCriterion("modifier in", values, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierNotIn(List<Long> values) {
			addCriterion("modifier not in", values, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierBetween(Long value1, Long value2) {
			addCriterion("modifier between", value1, value2, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierNotBetween(Long value1, Long value2) {
			addCriterion("modifier not between", value1, value2, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIsNull() {
			addCriterion("modify_time is null");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIsNotNull() {
			addCriterion("modify_time is not null");
			return (Criteria) this;
		}

		public Criteria andModifyTimeEqualTo(Date value) {
			addCriterion("modify_time =", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotEqualTo(Date value) {
			addCriterion("modify_time <>", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeGreaterThan(Date value) {
			addCriterion("modify_time >", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("modify_time >=", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeLessThan(Date value) {
			addCriterion("modify_time <", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
			addCriterion("modify_time <=", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIn(List<Date> values) {
			addCriterion("modify_time in", values, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotIn(List<Date> values) {
			addCriterion("modify_time not in", values, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeBetween(Date value1, Date value2) {
			addCriterion("modify_time between", value1, value2, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
			addCriterion("modify_time not between", value1, value2, "modifyTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table interest
	 * @mbggenerated  Mon Aug 29 09:30:58 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table interest
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 29 09:17:45 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}