package com.ray.demo.admin.model.master;

import java.io.Serializable;
import java.util.Date;

public class SysElement implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_element.id
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_element.ELE_GROUP_ID
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    private Long eleGroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_element.ELE_CODE
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    private String eleCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_element.ELE_NAME
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    private String eleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_element.ELE_KEY
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    private String eleKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_element.ORDER_NUM
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    private Integer orderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_element.STATUS_FLAG
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    private String statusFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_element.CRT_USER
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    private Long crtUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_element.CRT_DATETIME
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    private Date crtDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_element.UPD_USER
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    private Long updUser;
    
    
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_element.UPD_DATETIME
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    private Date updDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_element
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    private static final long serialVersionUID = 1L;
 

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_element.id
     *
     * @return the value of sys_element.id
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_element.id
     *
     * @param id the value for sys_element.id
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

   


	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_element.ELE_GROUP_ID
     *
     * @return the value of sys_element.ELE_GROUP_ID
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public Long getEleGroupId() {
        return eleGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_element.ELE_GROUP_ID
     *
     * @param eleGroupId the value for sys_element.ELE_GROUP_ID
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public void setEleGroupId(Long eleGroupId) {
        this.eleGroupId = eleGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_element.ELE_CODE
     *
     * @return the value of sys_element.ELE_CODE
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public String getEleCode() {
        return eleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_element.ELE_CODE
     *
     * @param eleCode the value for sys_element.ELE_CODE
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public void setEleCode(String eleCode) {
        this.eleCode = eleCode == null ? null : eleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_element.ELE_NAME
     *
     * @return the value of sys_element.ELE_NAME
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public String getEleName() {
        return eleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_element.ELE_NAME
     *
     * @param eleName the value for sys_element.ELE_NAME
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public void setEleName(String eleName) {
        this.eleName = eleName == null ? null : eleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_element.ELE_KEY
     *
     * @return the value of sys_element.ELE_KEY
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public String getEleKey() {
        return eleKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_element.ELE_KEY
     *
     * @param eleKey the value for sys_element.ELE_KEY
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public void setEleKey(String eleKey) {
        this.eleKey = eleKey == null ? null : eleKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_element.ORDER_NUM
     *
     * @return the value of sys_element.ORDER_NUM
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_element.ORDER_NUM
     *
     * @param orderNum the value for sys_element.ORDER_NUM
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_element.STATUS_FLAG
     *
     * @return the value of sys_element.STATUS_FLAG
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public String getStatusFlag() {
        return statusFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_element.STATUS_FLAG
     *
     * @param statusFlag the value for sys_element.STATUS_FLAG
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public void setStatusFlag(String statusFlag) {
        this.statusFlag = statusFlag == null ? null : statusFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_element.CRT_USER
     *
     * @return the value of sys_element.CRT_USER
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public Long getCrtUser() {
        return crtUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_element.CRT_USER
     *
     * @param crtUser the value for sys_element.CRT_USER
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public void setCrtUser(Long crtUser) {
        this.crtUser = crtUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_element.CRT_DATETIME
     *
     * @return the value of sys_element.CRT_DATETIME
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public Date getCrtDatetime() {
        return crtDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_element.CRT_DATETIME
     *
     * @param crtDatetime the value for sys_element.CRT_DATETIME
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public void setCrtDatetime(Date crtDatetime) {
        this.crtDatetime = crtDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_element.UPD_USER
     *
     * @return the value of sys_element.UPD_USER
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public Long getUpdUser() {
        return updUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_element.UPD_USER
     *
     * @param updUser the value for sys_element.UPD_USER
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public void setUpdUser(Long updUser) {
        this.updUser = updUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_element.UPD_DATETIME
     *
     * @return the value of sys_element.UPD_DATETIME
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public Date getUpdDatetime() {
        return updDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_element.UPD_DATETIME
     *
     * @param updDatetime the value for sys_element.UPD_DATETIME
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public void setUpdDatetime(Date updDatetime) {
        this.updDatetime = updDatetime;
    }
}