package com.ray.demo.admin.model.system;

import java.io.Serializable;

public class RolePermission implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_permission.id
	 * @mbggenerated  Mon Aug 08 17:00:34 CST 2016
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_permission.role_id
	 * @mbggenerated  Mon Aug 08 17:00:34 CST 2016
	 */
	private Long roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_permission.permission_id
	 * @mbggenerated  Mon Aug 08 17:00:34 CST 2016
	 */
	private Long permissionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table role_permission
	 * @mbggenerated  Mon Aug 08 17:00:34 CST 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_permission.id
	 * @return  the value of role_permission.id
	 * @mbggenerated  Mon Aug 08 17:00:34 CST 2016
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_permission.id
	 * @param id  the value for role_permission.id
	 * @mbggenerated  Mon Aug 08 17:00:34 CST 2016
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_permission.role_id
	 * @return  the value of role_permission.role_id
	 * @mbggenerated  Mon Aug 08 17:00:34 CST 2016
	 */
	public Long getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_permission.role_id
	 * @param roleId  the value for role_permission.role_id
	 * @mbggenerated  Mon Aug 08 17:00:34 CST 2016
	 */
	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_permission.permission_id
	 * @return  the value of role_permission.permission_id
	 * @mbggenerated  Mon Aug 08 17:00:34 CST 2016
	 */
	public Long getPermissionId() {
		return permissionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_permission.permission_id
	 * @param permissionId  the value for role_permission.permission_id
	 * @mbggenerated  Mon Aug 08 17:00:34 CST 2016
	 */
	public void setPermissionId(Long permissionId) {
		this.permissionId = permissionId;
	}
}