package com.ray.demo.admin.model.system;

import java.io.Serializable;
import java.util.Date;

public class SysRole implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role.id
	 * @mbggenerated  Mon Aug 08 17:00:34 CST 2016
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role.rolename
	 * @mbggenerated  Mon Aug 08 17:00:34 CST 2016
	 */
	private String rolename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role.createtime
	 * @mbggenerated  Mon Aug 08 17:00:34 CST 2016
	 */
	private Date createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role.updatetime
	 * @mbggenerated  Mon Aug 08 17:00:34 CST 2016
	 */
	private Date updatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role.creator
	 * @mbggenerated  Mon Aug 08 17:00:34 CST 2016
	 */
	private Long creator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role.updater
	 * @mbggenerated  Mon Aug 08 17:00:34 CST 2016
	 */
	private Long updater;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role.rolecode
	 * @mbggenerated  Mon Aug 08 17:00:34 CST 2016
	 */
	private String rolecode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_role
	 * @mbggenerated  Mon Aug 08 17:00:34 CST 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role.id
	 * @return  the value of sys_role.id
	 * @mbggenerated  Mon Aug 08 17:00:34 CST 2016
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role.id
	 * @param id  the value for sys_role.id
	 * @mbggenerated  Mon Aug 08 17:00:34 CST 2016
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role.rolename
	 * @return  the value of sys_role.rolename
	 * @mbggenerated  Mon Aug 08 17:00:34 CST 2016
	 */
	public String getRolename() {
		return rolename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role.rolename
	 * @param rolename  the value for sys_role.rolename
	 * @mbggenerated  Mon Aug 08 17:00:34 CST 2016
	 */
	public void setRolename(String rolename) {
		this.rolename = rolename == null ? null : rolename.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role.createtime
	 * @return  the value of sys_role.createtime
	 * @mbggenerated  Mon Aug 08 17:00:34 CST 2016
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role.createtime
	 * @param createtime  the value for sys_role.createtime
	 * @mbggenerated  Mon Aug 08 17:00:34 CST 2016
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role.updatetime
	 * @return  the value of sys_role.updatetime
	 * @mbggenerated  Mon Aug 08 17:00:34 CST 2016
	 */
	public Date getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role.updatetime
	 * @param updatetime  the value for sys_role.updatetime
	 * @mbggenerated  Mon Aug 08 17:00:34 CST 2016
	 */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role.creator
	 * @return  the value of sys_role.creator
	 * @mbggenerated  Mon Aug 08 17:00:34 CST 2016
	 */
	public Long getCreator() {
		return creator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role.creator
	 * @param creator  the value for sys_role.creator
	 * @mbggenerated  Mon Aug 08 17:00:34 CST 2016
	 */
	public void setCreator(Long creator) {
		this.creator = creator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role.updater
	 * @return  the value of sys_role.updater
	 * @mbggenerated  Mon Aug 08 17:00:34 CST 2016
	 */
	public Long getUpdater() {
		return updater;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role.updater
	 * @param updater  the value for sys_role.updater
	 * @mbggenerated  Mon Aug 08 17:00:34 CST 2016
	 */
	public void setUpdater(Long updater) {
		this.updater = updater;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role.rolecode
	 * @return  the value of sys_role.rolecode
	 * @mbggenerated  Mon Aug 08 17:00:34 CST 2016
	 */
	public String getRolecode() {
		return rolecode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role.rolecode
	 * @param rolecode  the value for sys_role.rolecode
	 * @mbggenerated  Mon Aug 08 17:00:34 CST 2016
	 */
	public void setRolecode(String rolecode) {
		this.rolecode = rolecode == null ? null : rolecode.trim();
	}
}