package com.ray.demo.admin.model.system;

import java.io.Serializable;

public class SysUserroleKey implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_userrole.user_id
	 * @mbggenerated  Mon Aug 08 17:00:34 CST 2016
	 */
	private Long userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_userrole.role_id
	 * @mbggenerated  Mon Aug 08 17:00:34 CST 2016
	 */
	private Long roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_userrole
	 * @mbggenerated  Mon Aug 08 17:00:34 CST 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_userrole.user_id
	 * @return  the value of sys_userrole.user_id
	 * @mbggenerated  Mon Aug 08 17:00:34 CST 2016
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_userrole.user_id
	 * @param userId  the value for sys_userrole.user_id
	 * @mbggenerated  Mon Aug 08 17:00:34 CST 2016
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_userrole.role_id
	 * @return  the value of sys_userrole.role_id
	 * @mbggenerated  Mon Aug 08 17:00:34 CST 2016
	 */
	public Long getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_userrole.role_id
	 * @param roleId  the value for sys_userrole.role_id
	 * @mbggenerated  Mon Aug 08 17:00:34 CST 2016
	 */
	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}
}