package com.ray.demo.admin.model.master;

import java.io.Serializable;
import java.util.Date;

public class Company implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.id
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.parent_id
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.name
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.email
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.english_name
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    private String englishName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.short_name
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    private String shortName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.worker_num
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    private Integer workerNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.license
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    private String license;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.expire_date
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    private Date expireDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.tax_num
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    private String taxNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.org_code
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    private String orgCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.found_date
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    private Date foundDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.reg_capital
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    private Integer regCapital;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.scope
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    private String scope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.phone
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.address
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.fax
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    private String fax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.postcode
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    private String postcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.reg_address
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    private String regAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.remark
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.legal_name
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    private String legalName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.legal_id
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    private String legalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.legal_phone
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    private String legalPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.legal_address
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    private String legalAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.legal_postcode
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    private String legalPostcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.legal_mobile
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    private String legalMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.legal_email
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    private String legalEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.contact_name
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    private String contactName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.contact_id
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    private String contactId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.contact_phone
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    private String contactPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.contact_address
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    private String contactAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.contact_postcode
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    private String contactPostcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.contact_mobile
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    private String contactMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.contact_email
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    private String contactEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.create_time
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.level
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.status
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.delete_flag
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    private Integer deleteFlag = 0;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.creator
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    private Long creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.modifier
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    private Long modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.modify_time
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.credit_code
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    private String creditCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.business_code_type
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    private Integer businessCodeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table company
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.id
     *
     * @return the value of company.id
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.id
     *
     * @param id the value for company.id
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.parent_id
     *
     * @return the value of company.parent_id
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.parent_id
     *
     * @param parentId the value for company.parent_id
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.name
     *
     * @return the value of company.name
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.name
     *
     * @param name the value for company.name
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.email
     *
     * @return the value of company.email
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.email
     *
     * @param email the value for company.email
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.english_name
     *
     * @return the value of company.english_name
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public String getEnglishName() {
        return englishName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.english_name
     *
     * @param englishName the value for company.english_name
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public void setEnglishName(String englishName) {
        this.englishName = englishName == null ? null : englishName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.short_name
     *
     * @return the value of company.short_name
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.short_name
     *
     * @param shortName the value for company.short_name
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public void setShortName(String shortName) {
        this.shortName = shortName == null ? null : shortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.worker_num
     *
     * @return the value of company.worker_num
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public Integer getWorkerNum() {
        return workerNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.worker_num
     *
     * @param workerNum the value for company.worker_num
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public void setWorkerNum(Integer workerNum) {
        this.workerNum = workerNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.license
     *
     * @return the value of company.license
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public String getLicense() {
        return license;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.license
     *
     * @param license the value for company.license
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public void setLicense(String license) {
        this.license = license == null ? null : license.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.expire_date
     *
     * @return the value of company.expire_date
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public Date getExpireDate() {
        return expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.expire_date
     *
     * @param expireDate the value for company.expire_date
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.tax_num
     *
     * @return the value of company.tax_num
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public String getTaxNum() {
        return taxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.tax_num
     *
     * @param taxNum the value for company.tax_num
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public void setTaxNum(String taxNum) {
        this.taxNum = taxNum == null ? null : taxNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.org_code
     *
     * @return the value of company.org_code
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.org_code
     *
     * @param orgCode the value for company.org_code
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode == null ? null : orgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.found_date
     *
     * @return the value of company.found_date
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public Date getFoundDate() {
        return foundDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.found_date
     *
     * @param foundDate the value for company.found_date
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public void setFoundDate(Date foundDate) {
        this.foundDate = foundDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.reg_capital
     *
     * @return the value of company.reg_capital
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public Integer getRegCapital() {
        return regCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.reg_capital
     *
     * @param regCapital the value for company.reg_capital
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public void setRegCapital(Integer regCapital) {
        this.regCapital = regCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.scope
     *
     * @return the value of company.scope
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public String getScope() {
        return scope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.scope
     *
     * @param scope the value for company.scope
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public void setScope(String scope) {
        this.scope = scope == null ? null : scope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.phone
     *
     * @return the value of company.phone
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.phone
     *
     * @param phone the value for company.phone
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.address
     *
     * @return the value of company.address
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.address
     *
     * @param address the value for company.address
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.fax
     *
     * @return the value of company.fax
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.fax
     *
     * @param fax the value for company.fax
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.postcode
     *
     * @return the value of company.postcode
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.postcode
     *
     * @param postcode the value for company.postcode
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode == null ? null : postcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.reg_address
     *
     * @return the value of company.reg_address
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public String getRegAddress() {
        return regAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.reg_address
     *
     * @param regAddress the value for company.reg_address
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public void setRegAddress(String regAddress) {
        this.regAddress = regAddress == null ? null : regAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.remark
     *
     * @return the value of company.remark
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.remark
     *
     * @param remark the value for company.remark
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.legal_name
     *
     * @return the value of company.legal_name
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public String getLegalName() {
        return legalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.legal_name
     *
     * @param legalName the value for company.legal_name
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public void setLegalName(String legalName) {
        this.legalName = legalName == null ? null : legalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.legal_id
     *
     * @return the value of company.legal_id
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public String getLegalId() {
        return legalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.legal_id
     *
     * @param legalId the value for company.legal_id
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public void setLegalId(String legalId) {
        this.legalId = legalId == null ? null : legalId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.legal_phone
     *
     * @return the value of company.legal_phone
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public String getLegalPhone() {
        return legalPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.legal_phone
     *
     * @param legalPhone the value for company.legal_phone
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public void setLegalPhone(String legalPhone) {
        this.legalPhone = legalPhone == null ? null : legalPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.legal_address
     *
     * @return the value of company.legal_address
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public String getLegalAddress() {
        return legalAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.legal_address
     *
     * @param legalAddress the value for company.legal_address
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public void setLegalAddress(String legalAddress) {
        this.legalAddress = legalAddress == null ? null : legalAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.legal_postcode
     *
     * @return the value of company.legal_postcode
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public String getLegalPostcode() {
        return legalPostcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.legal_postcode
     *
     * @param legalPostcode the value for company.legal_postcode
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public void setLegalPostcode(String legalPostcode) {
        this.legalPostcode = legalPostcode == null ? null : legalPostcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.legal_mobile
     *
     * @return the value of company.legal_mobile
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public String getLegalMobile() {
        return legalMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.legal_mobile
     *
     * @param legalMobile the value for company.legal_mobile
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public void setLegalMobile(String legalMobile) {
        this.legalMobile = legalMobile == null ? null : legalMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.legal_email
     *
     * @return the value of company.legal_email
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public String getLegalEmail() {
        return legalEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.legal_email
     *
     * @param legalEmail the value for company.legal_email
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public void setLegalEmail(String legalEmail) {
        this.legalEmail = legalEmail == null ? null : legalEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.contact_name
     *
     * @return the value of company.contact_name
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.contact_name
     *
     * @param contactName the value for company.contact_name
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public void setContactName(String contactName) {
        this.contactName = contactName == null ? null : contactName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.contact_id
     *
     * @return the value of company.contact_id
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public String getContactId() {
        return contactId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.contact_id
     *
     * @param contactId the value for company.contact_id
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public void setContactId(String contactId) {
        this.contactId = contactId == null ? null : contactId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.contact_phone
     *
     * @return the value of company.contact_phone
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.contact_phone
     *
     * @param contactPhone the value for company.contact_phone
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone == null ? null : contactPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.contact_address
     *
     * @return the value of company.contact_address
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public String getContactAddress() {
        return contactAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.contact_address
     *
     * @param contactAddress the value for company.contact_address
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public void setContactAddress(String contactAddress) {
        this.contactAddress = contactAddress == null ? null : contactAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.contact_postcode
     *
     * @return the value of company.contact_postcode
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public String getContactPostcode() {
        return contactPostcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.contact_postcode
     *
     * @param contactPostcode the value for company.contact_postcode
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public void setContactPostcode(String contactPostcode) {
        this.contactPostcode = contactPostcode == null ? null : contactPostcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.contact_mobile
     *
     * @return the value of company.contact_mobile
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public String getContactMobile() {
        return contactMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.contact_mobile
     *
     * @param contactMobile the value for company.contact_mobile
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public void setContactMobile(String contactMobile) {
        this.contactMobile = contactMobile == null ? null : contactMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.contact_email
     *
     * @return the value of company.contact_email
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public String getContactEmail() {
        return contactEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.contact_email
     *
     * @param contactEmail the value for company.contact_email
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public void setContactEmail(String contactEmail) {
        this.contactEmail = contactEmail == null ? null : contactEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.create_time
     *
     * @return the value of company.create_time
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.create_time
     *
     * @param createTime the value for company.create_time
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.level
     *
     * @return the value of company.level
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.level
     *
     * @param level the value for company.level
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.status
     *
     * @return the value of company.status
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.status
     *
     * @param status the value for company.status
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.delete_flag
     *
     * @return the value of company.delete_flag
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.delete_flag
     *
     * @param deleteFlag the value for company.delete_flag
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.creator
     *
     * @return the value of company.creator
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.creator
     *
     * @param creator the value for company.creator
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.modifier
     *
     * @return the value of company.modifier
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public Long getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.modifier
     *
     * @param modifier the value for company.modifier
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public void setModifier(Long modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.modify_time
     *
     * @return the value of company.modify_time
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.modify_time
     *
     * @param modifyTime the value for company.modify_time
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.credit_code
     *
     * @return the value of company.credit_code
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public String getCreditCode() {
        return creditCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.credit_code
     *
     * @param creditCode the value for company.credit_code
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public void setCreditCode(String creditCode) {
        this.creditCode = creditCode == null ? null : creditCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.business_code_type
     *
     * @return the value of company.business_code_type
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public Integer getBusinessCodeType() {
        return businessCodeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.business_code_type
     *
     * @param businessCodeType the value for company.business_code_type
     *
     * @mbggenerated Wed Aug 10 10:01:57 CST 2016
     */
    public void setBusinessCodeType(Integer businessCodeType) {
        this.businessCodeType = businessCodeType;
    }
}