package com.ray.demo.admin.model.master;

import java.io.Serializable;
import java.util.Date;

public class SellerBank implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_bank.id
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_bank.seller_id
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    private Long sellerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_bank.bank_name
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    private String bankName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_bank.bank_account
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    private String bankAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_bank.bank_address
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    private String bankAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_bank.delete_flag
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    private Integer deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_bank.creator
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    private Long creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_bank.create_time
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_bank.modifier
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    private Long modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_bank.modify_time
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table seller_bank
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_bank.id
     *
     * @return the value of seller_bank.id
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_bank.id
     *
     * @param id the value for seller_bank.id
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_bank.seller_id
     *
     * @return the value of seller_bank.seller_id
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    public Long getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_bank.seller_id
     *
     * @param sellerId the value for seller_bank.seller_id
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    public void setSellerId(Long sellerId) {
        this.sellerId = sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_bank.bank_name
     *
     * @return the value of seller_bank.bank_name
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_bank.bank_name
     *
     * @param bankName the value for seller_bank.bank_name
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_bank.bank_account
     *
     * @return the value of seller_bank.bank_account
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    public String getBankAccount() {
        return bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_bank.bank_account
     *
     * @param bankAccount the value for seller_bank.bank_account
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    public void setBankAccount(String bankAccount) {
        this.bankAccount = bankAccount == null ? null : bankAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_bank.bank_address
     *
     * @return the value of seller_bank.bank_address
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    public String getBankAddress() {
        return bankAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_bank.bank_address
     *
     * @param bankAddress the value for seller_bank.bank_address
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    public void setBankAddress(String bankAddress) {
        this.bankAddress = bankAddress == null ? null : bankAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_bank.delete_flag
     *
     * @return the value of seller_bank.delete_flag
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_bank.delete_flag
     *
     * @param deleteFlag the value for seller_bank.delete_flag
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_bank.creator
     *
     * @return the value of seller_bank.creator
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_bank.creator
     *
     * @param creator the value for seller_bank.creator
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_bank.create_time
     *
     * @return the value of seller_bank.create_time
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_bank.create_time
     *
     * @param createTime the value for seller_bank.create_time
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_bank.modifier
     *
     * @return the value of seller_bank.modifier
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    public Long getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_bank.modifier
     *
     * @param modifier the value for seller_bank.modifier
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    public void setModifier(Long modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_bank.modify_time
     *
     * @return the value of seller_bank.modify_time
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_bank.modify_time
     *
     * @param modifyTime the value for seller_bank.modify_time
     *
     * @mbggenerated Tue Aug 02 15:32:54 CST 2016
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}