package com.ray.demo.admin.model.master;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysElementExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_element
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_element
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_element
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_element
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public SysElementExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_element
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_element
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_element
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_element
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_element
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_element
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_element
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_element
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_element
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_element
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_element
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andEleGroupIdIsNull() {
            addCriterion("ELE_GROUP_ID is null");
            return (Criteria) this;
        }

        public Criteria andEleGroupIdIsNotNull() {
            addCriterion("ELE_GROUP_ID is not null");
            return (Criteria) this;
        }

        public Criteria andEleGroupIdEqualTo(Long value) {
            addCriterion("ELE_GROUP_ID =", value, "eleGroupId");
            return (Criteria) this;
        }

        public Criteria andEleGroupIdNotEqualTo(Long value) {
            addCriterion("ELE_GROUP_ID <>", value, "eleGroupId");
            return (Criteria) this;
        }

        public Criteria andEleGroupIdGreaterThan(Long value) {
            addCriterion("ELE_GROUP_ID >", value, "eleGroupId");
            return (Criteria) this;
        }

        public Criteria andEleGroupIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ELE_GROUP_ID >=", value, "eleGroupId");
            return (Criteria) this;
        }

        public Criteria andEleGroupIdLessThan(Long value) {
            addCriterion("ELE_GROUP_ID <", value, "eleGroupId");
            return (Criteria) this;
        }

        public Criteria andEleGroupIdLessThanOrEqualTo(Long value) {
            addCriterion("ELE_GROUP_ID <=", value, "eleGroupId");
            return (Criteria) this;
        }

        public Criteria andEleGroupIdIn(List<Long> values) {
            addCriterion("ELE_GROUP_ID in", values, "eleGroupId");
            return (Criteria) this;
        }

        public Criteria andEleGroupIdNotIn(List<Long> values) {
            addCriterion("ELE_GROUP_ID not in", values, "eleGroupId");
            return (Criteria) this;
        }

        public Criteria andEleGroupIdBetween(Long value1, Long value2) {
            addCriterion("ELE_GROUP_ID between", value1, value2, "eleGroupId");
            return (Criteria) this;
        }

        public Criteria andEleGroupIdNotBetween(Long value1, Long value2) {
            addCriterion("ELE_GROUP_ID not between", value1, value2, "eleGroupId");
            return (Criteria) this;
        }

        public Criteria andEleCodeIsNull() {
            addCriterion("ELE_CODE is null");
            return (Criteria) this;
        }

        public Criteria andEleCodeIsNotNull() {
            addCriterion("ELE_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andEleCodeEqualTo(String value) {
            addCriterion("ELE_CODE =", value, "eleCode");
            return (Criteria) this;
        }

        public Criteria andEleCodeNotEqualTo(String value) {
            addCriterion("ELE_CODE <>", value, "eleCode");
            return (Criteria) this;
        }

        public Criteria andEleCodeGreaterThan(String value) {
            addCriterion("ELE_CODE >", value, "eleCode");
            return (Criteria) this;
        }

        public Criteria andEleCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ELE_CODE >=", value, "eleCode");
            return (Criteria) this;
        }

        public Criteria andEleCodeLessThan(String value) {
            addCriterion("ELE_CODE <", value, "eleCode");
            return (Criteria) this;
        }

        public Criteria andEleCodeLessThanOrEqualTo(String value) {
            addCriterion("ELE_CODE <=", value, "eleCode");
            return (Criteria) this;
        }

        public Criteria andEleCodeLike(String value) {
            addCriterion("ELE_CODE like", value, "eleCode");
            return (Criteria) this;
        }

        public Criteria andEleCodeNotLike(String value) {
            addCriterion("ELE_CODE not like", value, "eleCode");
            return (Criteria) this;
        }

        public Criteria andEleCodeIn(List<String> values) {
            addCriterion("ELE_CODE in", values, "eleCode");
            return (Criteria) this;
        }

        public Criteria andEleCodeNotIn(List<String> values) {
            addCriterion("ELE_CODE not in", values, "eleCode");
            return (Criteria) this;
        }

        public Criteria andEleCodeBetween(String value1, String value2) {
            addCriterion("ELE_CODE between", value1, value2, "eleCode");
            return (Criteria) this;
        }

        public Criteria andEleCodeNotBetween(String value1, String value2) {
            addCriterion("ELE_CODE not between", value1, value2, "eleCode");
            return (Criteria) this;
        }

        public Criteria andEleNameIsNull() {
            addCriterion("ELE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andEleNameIsNotNull() {
            addCriterion("ELE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andEleNameEqualTo(String value) {
            addCriterion("ELE_NAME =", value, "eleName");
            return (Criteria) this;
        }

        public Criteria andEleNameNotEqualTo(String value) {
            addCriterion("ELE_NAME <>", value, "eleName");
            return (Criteria) this;
        }

        public Criteria andEleNameGreaterThan(String value) {
            addCriterion("ELE_NAME >", value, "eleName");
            return (Criteria) this;
        }

        public Criteria andEleNameGreaterThanOrEqualTo(String value) {
            addCriterion("ELE_NAME >=", value, "eleName");
            return (Criteria) this;
        }

        public Criteria andEleNameLessThan(String value) {
            addCriterion("ELE_NAME <", value, "eleName");
            return (Criteria) this;
        }

        public Criteria andEleNameLessThanOrEqualTo(String value) {
            addCriterion("ELE_NAME <=", value, "eleName");
            return (Criteria) this;
        }

        public Criteria andEleNameLike(String value) {
            addCriterion("ELE_NAME like", value, "eleName");
            return (Criteria) this;
        }

        public Criteria andEleNameNotLike(String value) {
            addCriterion("ELE_NAME not like", value, "eleName");
            return (Criteria) this;
        }

        public Criteria andEleNameIn(List<String> values) {
            addCriterion("ELE_NAME in", values, "eleName");
            return (Criteria) this;
        }

        public Criteria andEleNameNotIn(List<String> values) {
            addCriterion("ELE_NAME not in", values, "eleName");
            return (Criteria) this;
        }

        public Criteria andEleNameBetween(String value1, String value2) {
            addCriterion("ELE_NAME between", value1, value2, "eleName");
            return (Criteria) this;
        }

        public Criteria andEleNameNotBetween(String value1, String value2) {
            addCriterion("ELE_NAME not between", value1, value2, "eleName");
            return (Criteria) this;
        }

        public Criteria andEleKeyIsNull() {
            addCriterion("ELE_KEY is null");
            return (Criteria) this;
        }

        public Criteria andEleKeyIsNotNull() {
            addCriterion("ELE_KEY is not null");
            return (Criteria) this;
        }

        public Criteria andEleKeyEqualTo(String value) {
            addCriterion("ELE_KEY =", value, "eleKey");
            return (Criteria) this;
        }

        public Criteria andEleKeyNotEqualTo(String value) {
            addCriterion("ELE_KEY <>", value, "eleKey");
            return (Criteria) this;
        }

        public Criteria andEleKeyGreaterThan(String value) {
            addCriterion("ELE_KEY >", value, "eleKey");
            return (Criteria) this;
        }

        public Criteria andEleKeyGreaterThanOrEqualTo(String value) {
            addCriterion("ELE_KEY >=", value, "eleKey");
            return (Criteria) this;
        }

        public Criteria andEleKeyLessThan(String value) {
            addCriterion("ELE_KEY <", value, "eleKey");
            return (Criteria) this;
        }

        public Criteria andEleKeyLessThanOrEqualTo(String value) {
            addCriterion("ELE_KEY <=", value, "eleKey");
            return (Criteria) this;
        }

        public Criteria andEleKeyLike(String value) {
            addCriterion("ELE_KEY like", value, "eleKey");
            return (Criteria) this;
        }

        public Criteria andEleKeyNotLike(String value) {
            addCriterion("ELE_KEY not like", value, "eleKey");
            return (Criteria) this;
        }

        public Criteria andEleKeyIn(List<String> values) {
            addCriterion("ELE_KEY in", values, "eleKey");
            return (Criteria) this;
        }

        public Criteria andEleKeyNotIn(List<String> values) {
            addCriterion("ELE_KEY not in", values, "eleKey");
            return (Criteria) this;
        }

        public Criteria andEleKeyBetween(String value1, String value2) {
            addCriterion("ELE_KEY between", value1, value2, "eleKey");
            return (Criteria) this;
        }

        public Criteria andEleKeyNotBetween(String value1, String value2) {
            addCriterion("ELE_KEY not between", value1, value2, "eleKey");
            return (Criteria) this;
        }

        public Criteria andOrderNumIsNull() {
            addCriterion("ORDER_NUM is null");
            return (Criteria) this;
        }

        public Criteria andOrderNumIsNotNull() {
            addCriterion("ORDER_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andOrderNumEqualTo(Integer value) {
            addCriterion("ORDER_NUM =", value, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumNotEqualTo(Integer value) {
            addCriterion("ORDER_NUM <>", value, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumGreaterThan(Integer value) {
            addCriterion("ORDER_NUM >", value, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("ORDER_NUM >=", value, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumLessThan(Integer value) {
            addCriterion("ORDER_NUM <", value, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumLessThanOrEqualTo(Integer value) {
            addCriterion("ORDER_NUM <=", value, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumIn(List<Integer> values) {
            addCriterion("ORDER_NUM in", values, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumNotIn(List<Integer> values) {
            addCriterion("ORDER_NUM not in", values, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumBetween(Integer value1, Integer value2) {
            addCriterion("ORDER_NUM between", value1, value2, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumNotBetween(Integer value1, Integer value2) {
            addCriterion("ORDER_NUM not between", value1, value2, "orderNum");
            return (Criteria) this;
        }

        public Criteria andStatusFlagIsNull() {
            addCriterion("STATUS_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andStatusFlagIsNotNull() {
            addCriterion("STATUS_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andStatusFlagEqualTo(String value) {
            addCriterion("STATUS_FLAG =", value, "statusFlag");
            return (Criteria) this;
        }

        public Criteria andStatusFlagNotEqualTo(String value) {
            addCriterion("STATUS_FLAG <>", value, "statusFlag");
            return (Criteria) this;
        }

        public Criteria andStatusFlagGreaterThan(String value) {
            addCriterion("STATUS_FLAG >", value, "statusFlag");
            return (Criteria) this;
        }

        public Criteria andStatusFlagGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS_FLAG >=", value, "statusFlag");
            return (Criteria) this;
        }

        public Criteria andStatusFlagLessThan(String value) {
            addCriterion("STATUS_FLAG <", value, "statusFlag");
            return (Criteria) this;
        }

        public Criteria andStatusFlagLessThanOrEqualTo(String value) {
            addCriterion("STATUS_FLAG <=", value, "statusFlag");
            return (Criteria) this;
        }

        public Criteria andStatusFlagLike(String value) {
            addCriterion("STATUS_FLAG like", value, "statusFlag");
            return (Criteria) this;
        }

        public Criteria andStatusFlagNotLike(String value) {
            addCriterion("STATUS_FLAG not like", value, "statusFlag");
            return (Criteria) this;
        }

        public Criteria andStatusFlagIn(List<String> values) {
            addCriterion("STATUS_FLAG in", values, "statusFlag");
            return (Criteria) this;
        }

        public Criteria andStatusFlagNotIn(List<String> values) {
            addCriterion("STATUS_FLAG not in", values, "statusFlag");
            return (Criteria) this;
        }

        public Criteria andStatusFlagBetween(String value1, String value2) {
            addCriterion("STATUS_FLAG between", value1, value2, "statusFlag");
            return (Criteria) this;
        }

        public Criteria andStatusFlagNotBetween(String value1, String value2) {
            addCriterion("STATUS_FLAG not between", value1, value2, "statusFlag");
            return (Criteria) this;
        }

        public Criteria andCrtUserIsNull() {
            addCriterion("CRT_USER is null");
            return (Criteria) this;
        }

        public Criteria andCrtUserIsNotNull() {
            addCriterion("CRT_USER is not null");
            return (Criteria) this;
        }

        public Criteria andCrtUserEqualTo(Long value) {
            addCriterion("CRT_USER =", value, "crtUser");
            return (Criteria) this;
        }

        public Criteria andCrtUserNotEqualTo(Long value) {
            addCriterion("CRT_USER <>", value, "crtUser");
            return (Criteria) this;
        }

        public Criteria andCrtUserGreaterThan(Long value) {
            addCriterion("CRT_USER >", value, "crtUser");
            return (Criteria) this;
        }

        public Criteria andCrtUserGreaterThanOrEqualTo(Long value) {
            addCriterion("CRT_USER >=", value, "crtUser");
            return (Criteria) this;
        }

        public Criteria andCrtUserLessThan(Long value) {
            addCriterion("CRT_USER <", value, "crtUser");
            return (Criteria) this;
        }

        public Criteria andCrtUserLessThanOrEqualTo(Long value) {
            addCriterion("CRT_USER <=", value, "crtUser");
            return (Criteria) this;
        }

        public Criteria andCrtUserIn(List<Long> values) {
            addCriterion("CRT_USER in", values, "crtUser");
            return (Criteria) this;
        }

        public Criteria andCrtUserNotIn(List<Long> values) {
            addCriterion("CRT_USER not in", values, "crtUser");
            return (Criteria) this;
        }

        public Criteria andCrtUserBetween(Long value1, Long value2) {
            addCriterion("CRT_USER between", value1, value2, "crtUser");
            return (Criteria) this;
        }

        public Criteria andCrtUserNotBetween(Long value1, Long value2) {
            addCriterion("CRT_USER not between", value1, value2, "crtUser");
            return (Criteria) this;
        }

        public Criteria andCrtDatetimeIsNull() {
            addCriterion("CRT_DATETIME is null");
            return (Criteria) this;
        }

        public Criteria andCrtDatetimeIsNotNull() {
            addCriterion("CRT_DATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andCrtDatetimeEqualTo(Date value) {
            addCriterion("CRT_DATETIME =", value, "crtDatetime");
            return (Criteria) this;
        }

        public Criteria andCrtDatetimeNotEqualTo(Date value) {
            addCriterion("CRT_DATETIME <>", value, "crtDatetime");
            return (Criteria) this;
        }

        public Criteria andCrtDatetimeGreaterThan(Date value) {
            addCriterion("CRT_DATETIME >", value, "crtDatetime");
            return (Criteria) this;
        }

        public Criteria andCrtDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CRT_DATETIME >=", value, "crtDatetime");
            return (Criteria) this;
        }

        public Criteria andCrtDatetimeLessThan(Date value) {
            addCriterion("CRT_DATETIME <", value, "crtDatetime");
            return (Criteria) this;
        }

        public Criteria andCrtDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("CRT_DATETIME <=", value, "crtDatetime");
            return (Criteria) this;
        }

        public Criteria andCrtDatetimeIn(List<Date> values) {
            addCriterion("CRT_DATETIME in", values, "crtDatetime");
            return (Criteria) this;
        }

        public Criteria andCrtDatetimeNotIn(List<Date> values) {
            addCriterion("CRT_DATETIME not in", values, "crtDatetime");
            return (Criteria) this;
        }

        public Criteria andCrtDatetimeBetween(Date value1, Date value2) {
            addCriterion("CRT_DATETIME between", value1, value2, "crtDatetime");
            return (Criteria) this;
        }

        public Criteria andCrtDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("CRT_DATETIME not between", value1, value2, "crtDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdUserIsNull() {
            addCriterion("UPD_USER is null");
            return (Criteria) this;
        }

        public Criteria andUpdUserIsNotNull() {
            addCriterion("UPD_USER is not null");
            return (Criteria) this;
        }

        public Criteria andUpdUserEqualTo(Long value) {
            addCriterion("UPD_USER =", value, "updUser");
            return (Criteria) this;
        }

        public Criteria andUpdUserNotEqualTo(Long value) {
            addCriterion("UPD_USER <>", value, "updUser");
            return (Criteria) this;
        }

        public Criteria andUpdUserGreaterThan(Long value) {
            addCriterion("UPD_USER >", value, "updUser");
            return (Criteria) this;
        }

        public Criteria andUpdUserGreaterThanOrEqualTo(Long value) {
            addCriterion("UPD_USER >=", value, "updUser");
            return (Criteria) this;
        }

        public Criteria andUpdUserLessThan(Long value) {
            addCriterion("UPD_USER <", value, "updUser");
            return (Criteria) this;
        }

        public Criteria andUpdUserLessThanOrEqualTo(Long value) {
            addCriterion("UPD_USER <=", value, "updUser");
            return (Criteria) this;
        }

        public Criteria andUpdUserIn(List<Long> values) {
            addCriterion("UPD_USER in", values, "updUser");
            return (Criteria) this;
        }

        public Criteria andUpdUserNotIn(List<Long> values) {
            addCriterion("UPD_USER not in", values, "updUser");
            return (Criteria) this;
        }

        public Criteria andUpdUserBetween(Long value1, Long value2) {
            addCriterion("UPD_USER between", value1, value2, "updUser");
            return (Criteria) this;
        }

        public Criteria andUpdUserNotBetween(Long value1, Long value2) {
            addCriterion("UPD_USER not between", value1, value2, "updUser");
            return (Criteria) this;
        }

        public Criteria andUpdDatetimeIsNull() {
            addCriterion("UPD_DATETIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdDatetimeIsNotNull() {
            addCriterion("UPD_DATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdDatetimeEqualTo(Date value) {
            addCriterion("UPD_DATETIME =", value, "updDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdDatetimeNotEqualTo(Date value) {
            addCriterion("UPD_DATETIME <>", value, "updDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdDatetimeGreaterThan(Date value) {
            addCriterion("UPD_DATETIME >", value, "updDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPD_DATETIME >=", value, "updDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdDatetimeLessThan(Date value) {
            addCriterion("UPD_DATETIME <", value, "updDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("UPD_DATETIME <=", value, "updDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdDatetimeIn(List<Date> values) {
            addCriterion("UPD_DATETIME in", values, "updDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdDatetimeNotIn(List<Date> values) {
            addCriterion("UPD_DATETIME not in", values, "updDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdDatetimeBetween(Date value1, Date value2) {
            addCriterion("UPD_DATETIME between", value1, value2, "updDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("UPD_DATETIME not between", value1, value2, "updDatetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_element
     *
     * @mbggenerated do_not_delete_during_merge Fri Aug 05 12:36:22 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_element
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}