package com.ray.demo.admin.model.master;

import java.io.Serializable;
import java.util.Date;

public class SysElementGroup implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_element_group.id
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_element_group.ELE_GROUP_CODE
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    private String eleGroupCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_element_group.ELE_GROUP_NAME
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    private String eleGroupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_element_group.STATUS_FLAG
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    private String statusFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_element_group.CRT_USER
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    private Long crtUser;
   

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_element_group.CRT_DATETIME
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    private Date crtDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_element_group.UPD_USER
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    private Long updUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_element_group.UPD_DATETIME
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    private Date updDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_element_group
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_element_group.id
     *
     * @return the value of sys_element_group.id
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_element_group.id
     *
     * @param id the value for sys_element_group.id
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_element_group.ELE_GROUP_CODE
     *
     * @return the value of sys_element_group.ELE_GROUP_CODE
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public String getEleGroupCode() {
        return eleGroupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_element_group.ELE_GROUP_CODE
     *
     * @param eleGroupCode the value for sys_element_group.ELE_GROUP_CODE
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public void setEleGroupCode(String eleGroupCode) {
        this.eleGroupCode = eleGroupCode == null ? null : eleGroupCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_element_group.ELE_GROUP_NAME
     *
     * @return the value of sys_element_group.ELE_GROUP_NAME
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    
    public String getEleGroupName() {
        return eleGroupName;
    }

 
	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_element_group.ELE_GROUP_NAME
     *
     * @param eleGroupName the value for sys_element_group.ELE_GROUP_NAME
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public void setEleGroupName(String eleGroupName) {
        this.eleGroupName = eleGroupName == null ? null : eleGroupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_element_group.STATUS_FLAG
     *
     * @return the value of sys_element_group.STATUS_FLAG
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public String getStatusFlag() {
        return statusFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_element_group.STATUS_FLAG
     *
     * @param statusFlag the value for sys_element_group.STATUS_FLAG
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public void setStatusFlag(String statusFlag) {
        this.statusFlag = statusFlag == null ? null : statusFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_element_group.CRT_USER
     *
     * @return the value of sys_element_group.CRT_USER
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public Long getCrtUser() {
        return crtUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_element_group.CRT_USER
     *
     * @param crtUser the value for sys_element_group.CRT_USER
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public void setCrtUser(Long crtUser) {
        this.crtUser = crtUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_element_group.CRT_DATETIME
     *
     * @return the value of sys_element_group.CRT_DATETIME
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public Date getCrtDatetime() {
        return crtDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_element_group.CRT_DATETIME
     *
     * @param crtDatetime the value for sys_element_group.CRT_DATETIME
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public void setCrtDatetime(Date crtDatetime) {
        this.crtDatetime = crtDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_element_group.UPD_USER
     *
     * @return the value of sys_element_group.UPD_USER
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public Long getUpdUser() {
        return updUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_element_group.UPD_USER
     *
     * @param updUser the value for sys_element_group.UPD_USER
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public void setUpdUser(Long updUser) {
        this.updUser = updUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_element_group.UPD_DATETIME
     *
     * @return the value of sys_element_group.UPD_DATETIME
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public Date getUpdDatetime() {
        return updDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_element_group.UPD_DATETIME
     *
     * @param updDatetime the value for sys_element_group.UPD_DATETIME
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public void setUpdDatetime(Date updDatetime) {
        this.updDatetime = updDatetime;
    }
}