package com.ray.demo.admin.model.master;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysElementGroupExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_element_group
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_element_group
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_element_group
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_element_group
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public SysElementGroupExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_element_group
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_element_group
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_element_group
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_element_group
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_element_group
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_element_group
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_element_group
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_element_group
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_element_group
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_element_group
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_element_group
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andEleGroupCodeIsNull() {
            addCriterion("ELE_GROUP_CODE is null");
            return (Criteria) this;
        }

        public Criteria andEleGroupCodeIsNotNull() {
            addCriterion("ELE_GROUP_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andEleGroupCodeEqualTo(String value) {
            addCriterion("ELE_GROUP_CODE =", value, "eleGroupCode");
            return (Criteria) this;
        }

        public Criteria andEleGroupCodeNotEqualTo(String value) {
            addCriterion("ELE_GROUP_CODE <>", value, "eleGroupCode");
            return (Criteria) this;
        }

        public Criteria andEleGroupCodeGreaterThan(String value) {
            addCriterion("ELE_GROUP_CODE >", value, "eleGroupCode");
            return (Criteria) this;
        }

        public Criteria andEleGroupCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ELE_GROUP_CODE >=", value, "eleGroupCode");
            return (Criteria) this;
        }

        public Criteria andEleGroupCodeLessThan(String value) {
            addCriterion("ELE_GROUP_CODE <", value, "eleGroupCode");
            return (Criteria) this;
        }

        public Criteria andEleGroupCodeLessThanOrEqualTo(String value) {
            addCriterion("ELE_GROUP_CODE <=", value, "eleGroupCode");
            return (Criteria) this;
        }

        public Criteria andEleGroupCodeLike(String value) {
            addCriterion("ELE_GROUP_CODE like", value, "eleGroupCode");
            return (Criteria) this;
        }

        public Criteria andEleGroupCodeNotLike(String value) {
            addCriterion("ELE_GROUP_CODE not like", value, "eleGroupCode");
            return (Criteria) this;
        }

        public Criteria andEleGroupCodeIn(List<String> values) {
            addCriterion("ELE_GROUP_CODE in", values, "eleGroupCode");
            return (Criteria) this;
        }

        public Criteria andEleGroupCodeNotIn(List<String> values) {
            addCriterion("ELE_GROUP_CODE not in", values, "eleGroupCode");
            return (Criteria) this;
        }

        public Criteria andEleGroupCodeBetween(String value1, String value2) {
            addCriterion("ELE_GROUP_CODE between", value1, value2, "eleGroupCode");
            return (Criteria) this;
        }

        public Criteria andEleGroupCodeNotBetween(String value1, String value2) {
            addCriterion("ELE_GROUP_CODE not between", value1, value2, "eleGroupCode");
            return (Criteria) this;
        }

        public Criteria andEleGroupNameIsNull() {
            addCriterion("ELE_GROUP_NAME is null");
            return (Criteria) this;
        }

        public Criteria andEleGroupNameIsNotNull() {
            addCriterion("ELE_GROUP_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andEleGroupNameEqualTo(String value) {
            addCriterion("ELE_GROUP_NAME =", value, "eleGroupName");
            return (Criteria) this;
        }

        public Criteria andEleGroupNameNotEqualTo(String value) {
            addCriterion("ELE_GROUP_NAME <>", value, "eleGroupName");
            return (Criteria) this;
        }

        public Criteria andEleGroupNameGreaterThan(String value) {
            addCriterion("ELE_GROUP_NAME >", value, "eleGroupName");
            return (Criteria) this;
        }

        public Criteria andEleGroupNameGreaterThanOrEqualTo(String value) {
            addCriterion("ELE_GROUP_NAME >=", value, "eleGroupName");
            return (Criteria) this;
        }

        public Criteria andEleGroupNameLessThan(String value) {
            addCriterion("ELE_GROUP_NAME <", value, "eleGroupName");
            return (Criteria) this;
        }

        public Criteria andEleGroupNameLessThanOrEqualTo(String value) {
            addCriterion("ELE_GROUP_NAME <=", value, "eleGroupName");
            return (Criteria) this;
        }

        public Criteria andEleGroupNameLike(String value) {
            addCriterion("ELE_GROUP_NAME like", value, "eleGroupName");
            return (Criteria) this;
        }

        public Criteria andEleGroupNameNotLike(String value) {
            addCriterion("ELE_GROUP_NAME not like", value, "eleGroupName");
            return (Criteria) this;
        }

        public Criteria andEleGroupNameIn(List<String> values) {
            addCriterion("ELE_GROUP_NAME in", values, "eleGroupName");
            return (Criteria) this;
        }

        public Criteria andEleGroupNameNotIn(List<String> values) {
            addCriterion("ELE_GROUP_NAME not in", values, "eleGroupName");
            return (Criteria) this;
        }

        public Criteria andEleGroupNameBetween(String value1, String value2) {
            addCriterion("ELE_GROUP_NAME between", value1, value2, "eleGroupName");
            return (Criteria) this;
        }

        public Criteria andEleGroupNameNotBetween(String value1, String value2) {
            addCriterion("ELE_GROUP_NAME not between", value1, value2, "eleGroupName");
            return (Criteria) this;
        }

        public Criteria andStatusFlagIsNull() {
            addCriterion("STATUS_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andStatusFlagIsNotNull() {
            addCriterion("STATUS_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andStatusFlagEqualTo(String value) {
            addCriterion("STATUS_FLAG =", value, "statusFlag");
            return (Criteria) this;
        }

        public Criteria andStatusFlagNotEqualTo(String value) {
            addCriterion("STATUS_FLAG <>", value, "statusFlag");
            return (Criteria) this;
        }

        public Criteria andStatusFlagGreaterThan(String value) {
            addCriterion("STATUS_FLAG >", value, "statusFlag");
            return (Criteria) this;
        }

        public Criteria andStatusFlagGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS_FLAG >=", value, "statusFlag");
            return (Criteria) this;
        }

        public Criteria andStatusFlagLessThan(String value) {
            addCriterion("STATUS_FLAG <", value, "statusFlag");
            return (Criteria) this;
        }

        public Criteria andStatusFlagLessThanOrEqualTo(String value) {
            addCriterion("STATUS_FLAG <=", value, "statusFlag");
            return (Criteria) this;
        }

        public Criteria andStatusFlagLike(String value) {
            addCriterion("STATUS_FLAG like", value, "statusFlag");
            return (Criteria) this;
        }

        public Criteria andStatusFlagNotLike(String value) {
            addCriterion("STATUS_FLAG not like", value, "statusFlag");
            return (Criteria) this;
        }

        public Criteria andStatusFlagIn(List<String> values) {
            addCriterion("STATUS_FLAG in", values, "statusFlag");
            return (Criteria) this;
        }

        public Criteria andStatusFlagNotIn(List<String> values) {
            addCriterion("STATUS_FLAG not in", values, "statusFlag");
            return (Criteria) this;
        }

        public Criteria andStatusFlagBetween(String value1, String value2) {
            addCriterion("STATUS_FLAG between", value1, value2, "statusFlag");
            return (Criteria) this;
        }

        public Criteria andStatusFlagNotBetween(String value1, String value2) {
            addCriterion("STATUS_FLAG not between", value1, value2, "statusFlag");
            return (Criteria) this;
        }

        public Criteria andCrtUserIsNull() {
            addCriterion("CRT_USER is null");
            return (Criteria) this;
        }

        public Criteria andCrtUserIsNotNull() {
            addCriterion("CRT_USER is not null");
            return (Criteria) this;
        }

        public Criteria andCrtUserEqualTo(Long value) {
            addCriterion("CRT_USER =", value, "crtUser");
            return (Criteria) this;
        }

        public Criteria andCrtUserNotEqualTo(Long value) {
            addCriterion("CRT_USER <>", value, "crtUser");
            return (Criteria) this;
        }

        public Criteria andCrtUserGreaterThan(Long value) {
            addCriterion("CRT_USER >", value, "crtUser");
            return (Criteria) this;
        }

        public Criteria andCrtUserGreaterThanOrEqualTo(Long value) {
            addCriterion("CRT_USER >=", value, "crtUser");
            return (Criteria) this;
        }

        public Criteria andCrtUserLessThan(Long value) {
            addCriterion("CRT_USER <", value, "crtUser");
            return (Criteria) this;
        }

        public Criteria andCrtUserLessThanOrEqualTo(Long value) {
            addCriterion("CRT_USER <=", value, "crtUser");
            return (Criteria) this;
        }

        public Criteria andCrtUserIn(List<Long> values) {
            addCriterion("CRT_USER in", values, "crtUser");
            return (Criteria) this;
        }

        public Criteria andCrtUserNotIn(List<Long> values) {
            addCriterion("CRT_USER not in", values, "crtUser");
            return (Criteria) this;
        }

        public Criteria andCrtUserBetween(Long value1, Long value2) {
            addCriterion("CRT_USER between", value1, value2, "crtUser");
            return (Criteria) this;
        }

        public Criteria andCrtUserNotBetween(Long value1, Long value2) {
            addCriterion("CRT_USER not between", value1, value2, "crtUser");
            return (Criteria) this;
        }

        public Criteria andCrtDatetimeIsNull() {
            addCriterion("CRT_DATETIME is null");
            return (Criteria) this;
        }

        public Criteria andCrtDatetimeIsNotNull() {
            addCriterion("CRT_DATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andCrtDatetimeEqualTo(Date value) {
            addCriterion("CRT_DATETIME =", value, "crtDatetime");
            return (Criteria) this;
        }

        public Criteria andCrtDatetimeNotEqualTo(Date value) {
            addCriterion("CRT_DATETIME <>", value, "crtDatetime");
            return (Criteria) this;
        }

        public Criteria andCrtDatetimeGreaterThan(Date value) {
            addCriterion("CRT_DATETIME >", value, "crtDatetime");
            return (Criteria) this;
        }

        public Criteria andCrtDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CRT_DATETIME >=", value, "crtDatetime");
            return (Criteria) this;
        }

        public Criteria andCrtDatetimeLessThan(Date value) {
            addCriterion("CRT_DATETIME <", value, "crtDatetime");
            return (Criteria) this;
        }

        public Criteria andCrtDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("CRT_DATETIME <=", value, "crtDatetime");
            return (Criteria) this;
        }

        public Criteria andCrtDatetimeIn(List<Date> values) {
            addCriterion("CRT_DATETIME in", values, "crtDatetime");
            return (Criteria) this;
        }

        public Criteria andCrtDatetimeNotIn(List<Date> values) {
            addCriterion("CRT_DATETIME not in", values, "crtDatetime");
            return (Criteria) this;
        }

        public Criteria andCrtDatetimeBetween(Date value1, Date value2) {
            addCriterion("CRT_DATETIME between", value1, value2, "crtDatetime");
            return (Criteria) this;
        }

        public Criteria andCrtDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("CRT_DATETIME not between", value1, value2, "crtDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdUserIsNull() {
            addCriterion("UPD_USER is null");
            return (Criteria) this;
        }

        public Criteria andUpdUserIsNotNull() {
            addCriterion("UPD_USER is not null");
            return (Criteria) this;
        }

        public Criteria andUpdUserEqualTo(Long value) {
            addCriterion("UPD_USER =", value, "updUser");
            return (Criteria) this;
        }

        public Criteria andUpdUserNotEqualTo(Long value) {
            addCriterion("UPD_USER <>", value, "updUser");
            return (Criteria) this;
        }

        public Criteria andUpdUserGreaterThan(Long value) {
            addCriterion("UPD_USER >", value, "updUser");
            return (Criteria) this;
        }

        public Criteria andUpdUserGreaterThanOrEqualTo(Long value) {
            addCriterion("UPD_USER >=", value, "updUser");
            return (Criteria) this;
        }

        public Criteria andUpdUserLessThan(Long value) {
            addCriterion("UPD_USER <", value, "updUser");
            return (Criteria) this;
        }

        public Criteria andUpdUserLessThanOrEqualTo(Long value) {
            addCriterion("UPD_USER <=", value, "updUser");
            return (Criteria) this;
        }

        public Criteria andUpdUserIn(List<Long> values) {
            addCriterion("UPD_USER in", values, "updUser");
            return (Criteria) this;
        }

        public Criteria andUpdUserNotIn(List<Long> values) {
            addCriterion("UPD_USER not in", values, "updUser");
            return (Criteria) this;
        }

        public Criteria andUpdUserBetween(Long value1, Long value2) {
            addCriterion("UPD_USER between", value1, value2, "updUser");
            return (Criteria) this;
        }

        public Criteria andUpdUserNotBetween(Long value1, Long value2) {
            addCriterion("UPD_USER not between", value1, value2, "updUser");
            return (Criteria) this;
        }

        public Criteria andUpdDatetimeIsNull() {
            addCriterion("UPD_DATETIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdDatetimeIsNotNull() {
            addCriterion("UPD_DATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdDatetimeEqualTo(Date value) {
            addCriterion("UPD_DATETIME =", value, "updDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdDatetimeNotEqualTo(Date value) {
            addCriterion("UPD_DATETIME <>", value, "updDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdDatetimeGreaterThan(Date value) {
            addCriterion("UPD_DATETIME >", value, "updDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPD_DATETIME >=", value, "updDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdDatetimeLessThan(Date value) {
            addCriterion("UPD_DATETIME <", value, "updDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("UPD_DATETIME <=", value, "updDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdDatetimeIn(List<Date> values) {
            addCriterion("UPD_DATETIME in", values, "updDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdDatetimeNotIn(List<Date> values) {
            addCriterion("UPD_DATETIME not in", values, "updDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdDatetimeBetween(Date value1, Date value2) {
            addCriterion("UPD_DATETIME between", value1, value2, "updDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("UPD_DATETIME not between", value1, value2, "updDatetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_element_group
     *
     * @mbggenerated do_not_delete_during_merge Fri Aug 05 12:36:22 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_element_group
     *
     * @mbggenerated Fri Aug 05 12:36:22 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}