'use strict';


angular.module('app', [
    '$idle',                   
    'ngAnimate',
    'ngCookies',
    'ngResource',
    'ngSanitize',
    'ngTouch',
    'ngStorage',
    'ui.router',
    'ui.bootstrap',
    'ui.load',
    'ui.jq',
    'ui.validate',
    'angularShiro',
    'oc.lazyLoad',
    'pascalprecht.translate',
	'restangular', 
	'dialogs.main',
	'toaster',
	'ngMask',
	//'ngWebSocket',
	'angular-storage',
	'ngSocket',
	//'angular-echarts',
	'eCharts',
	'ngLoadingSpinner',
	'disableAll',
	'angularFileUpload',
	'leasing.common',
	'ng-currency',
	'fcsa-number',
]);
